# Generated by Django 6.0.1 on 2026-01-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient'), ('RECEPTIONIST', 'Receptionist')], max_length=15, null=True),
        ),
    ]
