# Generated by Django 6.0.1 on 2026-01-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(choices=[('EMERGENCY MEDICINE', 'Emergency Medicine'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('FAMILY MEDICINE', 'Family Medicine'), ('PEDIATRICS', 'Pediatrics'), ('OBSTETRICS & GYNECOLOGY', 'Obstetrics & Gynecology'), ('SURGERY', 'Surgery'), ('ORTHOPEDICS', 'Orthopedics'), ('CARDIOLOGY', 'Cardiology'), ('NEUROLOGY', 'Neurology'), ('PSYCHIATRY', 'Psychiatry'), ('DERMATOLOGY', 'Dermatology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('ENT', 'Ear, Nose, and Throat (ENT)'), ('RADIOLOGY', 'Radiology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('ONCOLOGY', 'Oncology'), ('GASTROENTEROLOGY', 'Gastroenterology'), ('NEPHROLOGY', 'Nephrology'), ('PULMONOLOGY', 'Pulmonology'), ('UROLOGY', 'Urology'), ('ENDROCRINOLOGY', 'Endocrinology'), ('INFECTIOUS DISEASES', 'Infectious Diseases'), ('RHEUMATOLOGY', 'Rheumatology'), ('HEMATOLOGY', 'Hematology'), ('PATHOLOGY', 'Pathology'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
