# Generated by Django 6.0.1 on 2026-01-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_date', models.DateTimeField()),
                ('reason_for_visit', models.TextField()),
                ('encounter_type', models.CharField(choices=[('OUTPATIENT', 'Outpatient'), ('EMERGENCY', 'Emergency'), ('FOLLOWUP', 'Follow-up')], default='OUTPATIENT', max_length=15)),
                ('assessment', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('admission_decision', models.CharField(blank=True, choices=[('DISCHARGE', 'Discharge'), ('ADMIT', 'Admit'), ('OBSERVE', 'Observe(4-6 hours)')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
