# Generated by Django 6.0.1 on 2026-01-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Encounter', '0002_initial'),
        ('accounts', '0005_alter_doctorprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile'),
        ),
    ]
