# Generated by Django 6.0.1 on 2026-01-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingrecord',
            old_name='appointment',
            new_name='encounter',
        ),
    ]
