# Generated by Django 6.0.1 on 2026-01-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_rename_appointment_billingrecord_encounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrecord',
            name='patient',
        ),
    ]
