# Generated by Django 6.0.1 on 2026-01-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='encounter',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('ROUTINE', 'Routine Check-up'), ('FOLLOW_UP', 'Follow-up'), ('EMERGENCY', 'Emergency Visit')], default='ROUTINE', max_length=15),
        ),
    ]
