# Generated by Django 6.0.1 on 2026-01-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3, null=True)),
                ('allergies', models.TextField(blank=True, help_text='List patient allergies (medications, food, etc.)', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='Ongoing medical conditions (diabetes, hypertension, etc.)', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='List of current medications and dosages', null=True)),
                ('past_surgeries', models.TextField(blank=True, help_text='History of surgical procedures', null=True)),
                ('family_history', models.TextField(blank=True, help_text='Relevant family medical history', null=True)),
                ('immunizations', models.TextField(blank=True, help_text='Vaccination history', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional medical history notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='accounts.patientprofile')),
            ],
        ),
    ]
