# Generated by Django 6.0.1 on 2026-01-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_patientmedicalhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='cycle_length_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Average cycle length in days', null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='last_menstrual_period',
            field=models.DateField(blank=True, help_text='Date of last menstrual period (LMP)', null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='menopause_status',
            field=models.CharField(choices=[('PRE', 'Premenopausal'), ('PERI', 'Perimenopausal'), ('POST', 'Postmenopausal'), ('NA', 'Not Applicable')], default='NA', max_length=4),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='period_duration_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Average period duration in days', null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='personal_history',
            field=models.TextField(blank=True, help_text='if patient drinks alcohol, smokes, etc.', null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='typical_flow',
            field=models.CharField(blank=True, choices=[('LIGHT', 'Light'), ('MODERATE', 'Moderate'), ('HEAVY', 'Heavy')], max_length=8, null=True),
        ),
    ]
