# Generated by Django 6.0.1 on 2026-01-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_patientmedicalhistory_cycle_length_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicalhistory',
            name='cycle_length_days',
        ),
        migrations.RemoveField(
            model_name='patientmedicalhistory',
            name='last_menstrual_period',
        ),
        migrations.RemoveField(
            model_name='patientmedicalhistory',
            name='menopause_status',
        ),
        migrations.RemoveField(
            model_name='patientmedicalhistory',
            name='period_duration_days',
        ),
        migrations.RemoveField(
            model_name='patientmedicalhistory',
            name='typical_flow',
        ),
    ]
